mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('restaurant_app.urls'))
]

restaurant_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
   path('', views.MenuList.as_view(), name = 'home') 
]

restaurant_app/models.py
from django.db import models
from django.contrib.auth.models import User


MEAL_TYPE=(
    ("starters", "Starters"),
    ("salads", "Salads"),
    ("main_dishes", "Main Dishes"),
    ("deserts", "Deserts")
)

STATUS=(
    (0, "Unavailable"),
    (1, "Available")
)

class Item(models.Model):
    meal = models.CharField(max_length=1000, unique=True)
    descriptions = models.CharField(max_length=2000)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    meal_type = models.CharField(max_length=2000, choices=MEAL_TYPE)
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    status = models.IntegerField(choices=STATUS, default=0)
    date_created= models.DateTimeField(auto_now_add=True)
    date_updated= models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.meal

restaurant_app/views.py
from django.shortcuts import render
from django.views import generic
from .models import Item, MEAL_TYPE

class MenuList(generic.ListView):
    queryset = Item.objects.order_by("-date_created")
    template_name = "index.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["meals"] = MEAL_TYPE
        return context
class MenuItemDetail(generic.DetailView):
    model = Item
    template_name = "menu_item_detail.html"

restaurant_app/templates/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <h1> Arzo Restaurant Menu</h1>
        {% for meal in meals%}
            <h2>{{meal.1}}</h2>
            {%for m in item_list%}
                    <h3>{{m.meal}}</h3>
                        <p>{{m.descriptions}}</p>
                {% endfor %}
        {%endfor%}
        <script src="" async defer></script>
    </body>
</html>

restaurant_app/templates/menu_item_detail.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title></title>
        <meta name="description" content="">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" href="">
    </head>
    <body>
        <!--[if lt IE 7]>
            <p class="browsehappy">You are using an <strong>outdated</strong> browser. Please <a href="#">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        
        <script src="" async defer></script>
    </body>
</html>